### PR TITLE
Add carbon-relay daemon for Graphite HA setup

### PR DESCRIPTION
**Pull request by Duologic**
I'm setting up a HA Graphite/Carbon cluster. I'm making baby steps adding the carbon-relay daemon. Feedback will be appreciated.

- Adds option to disable each component (uwsgi, carbon-cache, carbon-relay)
- Adds basic relay-rules.conf file as needed by carbon-relay (still needs templating).

FYI, not tested on Debian.

I'm using this in https://github.com/Duologic/vagrant-ansible-graphite-statsd-example

### CODE REVIEW

**Comment by Duologic** [comment]
The CI failes because support for Ansible 2.1 and 2.2. I updated the `include` statements to `include_tasks` as afformentioned is deprecated. What is the plan for supporting multiple Ansible versions?

**Comment by nsg** [comment]
Over all, it looks good.

[include_tasks](https://docs.ansible.com/ansible/2.4/include_tasks_module.html) is still brand new and I like to support at least a few versions. If there is no way to disable the warnings for this specific task, we just have to live with the warnings. So keep `include` for now.

`listen` was also added in 2.2 so it will not work with Ansible 2.1, it is probably fine to remove the support for  2.1 these days, but if this is the only reason, I prefer to just rewrite it a little and remove the need for `listen` to keep 2.1 compatibility.

I will try to give this a try this weekend and compare some configuration against an actual production system at work and see if there is something clever to add :)

**Comment by Duologic** [comment]
Sure, I'll check out the warnings and see if we can hide them. I've seen it done before.

Edit: I've indeed seen this before, but that is on the `command` and `shell` modules, not on the include. I think we'll have to live with the warnings. I'll update the pull request.

**Comment by Duologic** [comment]
Seems like the 'listen' on the handler is only available since 2.2. Any suggestions on how to fix this?

**Comment by nsg** [comment]
I usually just triggers several handlers like this:

```
 - name: Install storage schemas
   template:
     src: storage-schemas.conf.j2
     dest: "{{ graphite_install_path }}/conf/storage-schemas.conf"
   notify:
     - restart carbon-cache
     - restart carbon-relay
```

This removed the need for `listen`.

**Comment by odyssey4me** [comment]
It'd be great to see this functionality merged. Can we expect an update to the PR at some point, or shall we close the PR?

**Comment by nsg** [comment]
I left it to give @Duologic a chance to update the PR, and then I forgot about it :)

I guess, I or even possible you @odyssey4me can base a new PR on top of this one. Just a few listen directives that needs to be replaced, alternative drop support for Ansible 2.1.

This PR probably also needs to be rebased on top of master for the CI to run correctly.

**Comment by Duologic** [comment]
I haven't worked on/with these playbooks for a long time. As suggested, @odyssey4me can rebase this and implement the workaround for the `listen` argument OR as Ansible 2.1 is EOL @nsg might consider dropping support and a rebase could be enough.

**Comment by Duologic** [comment]
Rebased the branch on master.

**Comment by Duologic** [comment]
I think the Ansible version matrix should be updated too, but I'm not very familiar with that. Which versions should we support? Which are still supported by Ansible/Redhat?

**Comment by Duologic** [comment]
The commits with the graphite update and the cluster_servers variable are not really required but I believe they won't do much harm either, on the contrary. Any feedback would be welcome.

**Comment by nsg** [comment]
Looks good!

> Which versions should we support? Which are still supported by Ansible/Redhat?

https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html
Looks like we an drop everything older then 2.5.

If you update the matrix to something like this,

```
  matrix:

    - ANSIBLE_VERSIONS="2.7.0" ANSIBLE_EXTRA_VARS_LIST="version=1.0.2"
    - ANSIBLE_VERSIONS="2.6.5" ANSIBLE_EXTRA_VARS_LIST="version=1.0.2"
    - ANSIBLE_VERSIONS="2.5.9" ANSIBLE_EXTRA_VARS_LIST="version=1.0.2"

    - ANSIBLE_VERSIONS="2.7.0" ANSIBLE_EXTRA_VARS_LIST="version=1.1.3"
    - ANSIBLE_VERSIONS="2.6.5" ANSIBLE_EXTRA_VARS_LIST="version=1.1.3"
    - ANSIBLE_VERSIONS="2.5.9" ANSIBLE_EXTRA_VARS_LIST="version=1.1.3"

    - ANSIBLE_VERSIONS="2.7.0" ANSIBLE_EXTRA_VARS_LIST="version=1.1.5"
    - ANSIBLE_VERSIONS="2.6.5" ANSIBLE_EXTRA_VARS_LIST="version=1.1.5"
    - ANSIBLE_VERSIONS="2.5.9" ANSIBLE_EXTRA_VARS_LIST="version=1.1.5"

```

... that would do it! :) ... If you do not have the time to do so to get it part of this PR, it's fine. I will merge it anyway. It's time to merge this soon, it has been here open for way to long. Once again, thanks!

**Comment by Duologic** [comment]
I'll pick it up somewhere this week.

**Comment by Duologic** [comment]
Here we go, I took the liberty of adding Ubuntu 18.04 to the mix.

**Comment by Duologic** [comment]
So, the CI fails to start Carbon version 1.1.5 on Ubuntu 14.04 (Trusty), Ansible 2.6 and 2.7 fail without much useful outpt, Ansible 2.5 gave a bit more output: https://travis-ci.org/nsg/ansible-graphite/jobs/488467234#L3307

The easy way out would be to stop supporting Trusty, LTS stops in 2019-04 anyway. What do you think?

**Comment by nsg** [comment]
I'm fine with dropping Trusty support.

**Comment by Duologic** [comment]
Looks like the TravisCI test script still requires Trusty, not a real problem but we might want to update that at some point.

**Comment by nsg** [comment]
It's TravisCI that's unreliable as usual :\ ... I have triggered 325.5 and 325.8 again.

https://travis-ci.org/nsg/ansible-graphite/jobs/489197450 looks like a possible real error on centos, but I will trigger it again to make sure.

**Comment by nsg** [comment]
All 3 failures where classic Travis connectivity problems, worked on a second try. Anything left from your part, should I merge? I'm happy.

**Comment by Duologic** [comment]
My comment was before the 'force push', I previously changed .travisci.yml to use Xenial instead of Trusty, but TravisCI timed out on all of them, [see build 324](https://travis-ci.org/nsg/ansible-graphite/builds/489191699).

Anyway, I don't have any more changes up my sleeve for now. ;-)

**Comment by nsg** [comment]
Perfect, all done :+1:

**Pull request merged**
