### PR TITLE
Xenial compat

### PR DESCRIPTION
**Pull request by tdac**
added Xenial compatibility

### CODE REVIEW

**Comment by tdac** [comment]
Added Systemd, meta data,  fixed a weird bug with with_items, fixed pip incompatibility that was intoduced with pip 7 - but limited that to Xenial with a 'when'. 

This works on my test machine and builds graphite, although it does have to be run twice or you get a Django DB error.  This is probably down to the previously reported idempotence issue already patched.  It fails on Travis due to there being no Ubuntu 16.04 docker image created for the test.   The Ubuntu 14.04 version seems to work - but Travis fails it without printing any obvious errors (just a status code 1 at the end - unless a warning is enough for it to fail?).

**Comment by nsg** [comment]
Thank you,

The tests are somewhat broken at the moment, I plan to replace Docker with LXD. It's a more sane system to test different OS installs, but Travis do not support LXD (their OS installs are ancient). I tried to use vanilla LXC a while back but I was unsuccessful to connect the the container, spent hours debugging that and finality give up. I have been waiting for them to upgrade to the latest Ubuntu LTS (almost a year old now) but considering that their default install still is the five years old 12.04 LTS I'm not that hopeful.

My plan is just to setup my own build environment but I have not prioritized that, you know life and stuff got in the way. Maybe a weekend project, we will see :)

**Comment by nsg** [comment]
Finally some time to work on this, I did a manual merge to solve a conflict.

Your changes: https://github.com/nsg/ansible-graphite/commit/5431963ad51d950b0cfee87e148be220ebc3bb14

Thank you!

**Comment by tdac** [comment]
Brilliant!  Thanks @nsg

**Pull request closed without merging**
